fix: .chezmoiremove with `*` when destDir is `/`
twpayne/chezmoi pull request #1660
Opened 2021-11-23 02:26 UTC by felipecrs

Fixes #1651

2021-11-23 04:18 UTC, twpayne requested changes
One small nit. Please also add a test for this.

2021-11-23 04:18 UTC, twpayne commented on internal/chezmoi/chezmoi.go
> +	if !strings.HasSuffix(s, suffix) {
It's a tiny bit, but I prefer to use positive logic where possible, i.e. if `s` already has suffix `suffix` then return `s`.

2021-11-23 06:20 UTC, felipecrs commented
![image](https://user-images.githubusercontent.com/29582865/142978959-dc4d24f4-b772-41f5-b9ea-33d14ac062fe.png)

The test works. I'm just not sure about the filename of it.

2021-11-24 04:12 UTC, twpayne approved these changes
Great, thank you!

2021-11-24 04:25 UTC, merged