Improve chezmoi cd command
twpayne/chezmoi pull request #2823
Opened 2023-03-05 21:25 UTC by twpayne

This potentially fixes #2821 by setting the `$PS1` environment variable and stopping `chezmoi cd` subshells from nesting.

Review appreciated on this.

2023-03-05 21:26 UTC, twpayne commented
cc @EvanCarroll

2023-03-05 22:08 UTC, EvanCarroll requested changes

2023-03-05 22:10 UTC, bradenhilton commented
I'm in favor of preventing subshell nesting. I don't think we should set the prompt, at least by default.

Alternatively, we could perhaps set it with a `cd.prompt` prefix in the config, which defaults to either `"chezmoi"` or an empty string.

Whatever way you look at it, we probably need a way to disable this for people who don't want/need it.

2023-03-06 04:10 UTC, halostatue commented on pkg/cmd/config.go
> +	runEnv = append(runEnv, "PS1=chezmoi> ")
@EvanCarroll Chezmoi is mostly shell-agnostic, so these would be…suboptimal, at best, for those of us who use fish, elvish, or some other shell as our `$SHELL`.

2023-03-06 04:13 UTC, halostatue commented on pkg/cmd/config.go
> +	runEnv = append(runEnv, "PS1=chezmoi> ")
@twpayne `PS1` is "only" used by POSIX-ish shells (zsh, bash, ksh, busybox, oilsh). (t)csh, fish, etc. do not use it, and it won’t help anything for those shells.

Like @bradenhilton, I don’t think we should be changing the prompt automatically.

2023-03-06 20:49 UTC, bradenhilton approved these changes

2023-03-06 20:49 UTC, twpayne commented
Thank you for the reviews. I agree that chezmoi should be shell agnostic and so have removed the setting of `$PS1`. I've kept the protection against nested `chezmoi cd` commands.

2023-03-06 21:13 UTC, halostatue approved these changes

2023-03-06 21:26 UTC, merged